[workspace]
members = [
    "bond_teller",
    "bonds_registry", 
    "cover_payment_manager",
    "cover_points",
    "cover_product",
    "data_provider",
    "executor",
    "faucet",
    "libraries",
    "pida",
    "policy_manager",
    "premium_pool",
    "registry",
    "risk_manager",
    "risk_strategy",
    "staking",
    "ve_pida", 
    "xp_locker"
]