[project]
authors = ["Nate"]
entry = "main.sw"
license = "Apache-2.0"
name = "ve_pida"

[dependencies]
locker_abi = { path = "../abis/locker_abi" }
nft = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.8.0" }
