[project]
authors = ["Nate"]
entry = "main.sw"
license = "Apache-2.0"
name = "bonds_registry"

[dependencies]
token_abi = { path = "../abis/token_abi" }
bond_registry_abi = { path = "../abis/bond_registry_abi" }
